version: '3.3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8010"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8010:8010
      - 5676:5678
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pet_store_docker
      - POSTGRES_PASSWORD=pet_store_docker
      - POSTGRES_DB=pet_store_docker_dev
    ports:
      - "5457:5432"  

volumes:
  postgres_data:
