# Generated by Django 4.1.7 on 2023-06-08 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExameMedico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "diagnostico",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("data_exame", models.DateField()),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("Dinheiro", "Dinheiro"),
                            ("Cartão", "Cartão"),
                            ("Pix", "Pix"),
                        ],
                        default="Cartão",
                        max_length=8,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
            ],
            options={
                "db_table": "exame_medico",
            },
        ),
        migrations.CreateModel(
            name="TipoExame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "tipo_exame",
            },
        ),
    ]
