# Generated by Django 4.1.7 on 2023-05-20 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0003_alter_pet_raca'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_exame',
            },
        ),
        migrations.CreateModel(
            name='ExameMedico',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('diagnostico', models.TextField(max_length=500)),
                ('data_exame', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão'), ('Pix', 'Pix')], default='Cartão', max_length=8)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.pet')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exame_medico.tipoexame')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.veterinario')),
            ],
            options={
                'db_table': 'exame_medico',
            },
        ),
    ]
