# Generated by Django 4.1.7 on 2023-06-08 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pet", "0001_initial"),
        ("exame_medico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examemedico",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pet.pet"
            ),
        ),
        migrations.AddField(
            model_name="examemedico",
            name="tipo_exame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exame_medico.tipoexame"
            ),
        ),
    ]
