# Generated by Django 4.1.7 on 2023-06-17 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exame_medico", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExameMedico",
        ),
        migrations.DeleteModel(
            name="TipoExame",
        ),
    ]
