# Generated by Django 4.1.7 on 2023-08-06 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_tutor", models.BooleanField(default=False)),
                ("is_veterinario", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tutors",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("celular", models.CharField(blank=True, max_length=11, null=True)),
                ("cpf", models.CharField(blank=True, max_length=11, null=True)),
                ("rg", models.CharField(blank=True, max_length=11, null=True)),
                ("rua", models.CharField(blank=True, max_length=50, null=True)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                ("complemento", models.CharField(blank=True, max_length=20, null=True)),
                ("bairro", models.CharField(blank=True, max_length=15, null=True)),
                ("cidade", models.CharField(blank=True, max_length=20, null=True)),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                ("observacao", models.TextField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Veterinario",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="veterinarios",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("nome_clinica", models.CharField(max_length=50)),
                ("celular", models.CharField(blank=True, max_length=11, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
    ]
