# Generated by Django 4.1.7 on 2023-08-06 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="tutors",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="veterinario",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="veterinarios",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
