# Generated by Django 4.1.7 on 2023-06-17 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exame_medico", "0004_delete_examemedico_delete_tipoexame"),
        ("pet", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="especie",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="raca",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="tutor",
        ),
        migrations.RemoveField(
            model_name="raca",
            name="especie",
        ),
        migrations.DeleteModel(
            name="Especie",
        ),
        migrations.DeleteModel(
            name="Pet",
        ),
        migrations.DeleteModel(
            name="Raca",
        ),
    ]
